### ISSUE TITLE
Duplication of highlights and annotations

### ISSUE THREAD

**Issue by bpriyum** [weichenw/obsidian-hypothesis-plugin#19] opened 2021-11-19 13:40 UTC
Hi,

First of all I would like to thank you for making this plugin. This has made live a lot easier for me. However, there are a few things I would like to bring to your attention. 
1. The highlights are being imported in duplicates. 
2. I don't know if this by design. An annotation is followed by the highlighted passage rather than the highlighted passage being followed by the annotation as in hypothes.is.
3. All highlights are not being imported. My highlights from the last 7 days has not be imported. 

Thanks again for your effort. Even with the above issues this plugin is a great help.

Cheers

Priyam

**Comment by weichenw** [comment] 2021-11-20 13:28
Hi Priyam,

1. The highlights are being imported in duplicates. -> _**I just tried and it seems to work fine.  How is it duplicating?**_

2. I don't know if this by design. An annotation is followed by the highlighted passage rather than the highlighted passage being followed by the annotation as in hypothes.is. -> _**Check out the nunjucks template if you want to change the way the highlights/annotations are created. Having said that, in Hypothesis annotations are stored under highlights.**_

3. All highlights are not being imported. My highlights from the last 7 days has not be imported. -> _**Seems to work for me. Cna you check if you are getting error in the developer console?**_

Cheers

**Comment by bpriyum** [comment] 2021-11-20 17:03
Thanks for your prompt reply. Much appreciated 🙏❤️.

1. Say I have 7 annotation. After syncing, I can see these annotations
listed as 1, 2, 3.....7 then again 1, 2, 3.....7.

2. As you pointed out, in hypothesis the annotations are under the
highlights. But, when imported , the highlights are under annotations.

3. I don't know why all my highlights are not being imported. I even tried
reset and syncing again but still it didn't work.

I am not a coder so It will take me some time to understand the nunjucks.

Again thanks for making this plugin.

Cheers.

**Comment by weichenw** [comment] 2021-11-21 04:14
I can only suggest that you delete all the generated files and reset the sync. Copy the nunjucks template below. Then sync everything again.

Please make sure you got the latest version as well.

Below is the default nunjucks template that I am using personally. You can copy and paste it into your configuration.

{% if is_new_article %}# {{title}}

## Metadata
{% if author %}- Author: [{{author}}]({{authorUrl}}){% endif %}
- Title: {{title}}
{% if url %}- Reference: {{url}}{% endif %}
- Category: #article{% endif %}

{% if is_new_article -%}## Highlights{%- endif %}
{% for highlight in highlights -%}- {{highlight.text}} — [Updated on {{highlight.updated}}]({{highlight.incontext}})
{% if highlight.tags | length %}   - Tags: {% for tag in highlight.tags -%}#{{tag| replace(" ", "-")}} {%- endfor %}{%- endif %}
{% if highlight.annotation %}   - Annotation: {{highlight.annotation}}{%- endif -%}{%- endfor -%}

**Comment by mschrader15** [comment] 2021-11-30 14:58
Hi @weichenw , Thanks so much for making this plugin! 

Unfortunately, I am seeing the same behavior that @bpriyum described. I tried deleting and syncing multiple times, as well as manipulating the template.

**Comment by weichenw** [comment] 2021-11-30 22:19
Hi, there is a possibility that an error occurs before all the sync finishes. Could you please check if there are errors in the console?

https://forum.obsidian.md/t/how-to-access-the-console/16703

I just tried groups. It seems to work fine.

**Comment by mschrader15** [comment] 2021-12-01 04:01
No errors in the console. Same with me not having annotations for the past couple of days as well. 

I wonder if it is on Hypothesis side...

**Comment by weichenw** [comment] 2021-12-01 11:44
> No errors in the console. To be clear, I am seeing both the duplication error and the not-pulling-recent error.
> 
> I wonder if it is on Hypothesis side...

Unfortunately, I am unable to replicate this issue. I have tried several times it works for me.

Just to confirm that you are on the latest version, reset the history and delete all the files before resyncing everything again.

**Comment by mschrader15** [comment] 2021-12-01 14:13
I have traced the issue down to the pagination of API query in `getHighlights`

This is what the function looks like in my sources, which differs from https://github.com/weichenw/obsidian-hypothesis-plugin/blob/d209b3c00faaaf02b6c6529a97cb529c2d48720e/src/api/api.ts#L50

```
async getHighlights(t) {
                    let n, i = 0, r = 1e3, o = !0, s = [];
                    const a = t ? `&search_after=${e.moment.utc(t).format()}` : "";
                    for (let l = 0; l < r && i <= r; i += 2) {
                        try {
                            n = await fetch(`${this.baseUrl}/search?user=${this.userid}&offset=${i}&limit=200&sort=updated&order=asc` + a, {
                                headers: Object.assign({}, this.getHeaders())
                            })
                        } catch (t) {
                            return new e.Notice("Error occurs. Please check your API token and try again."),
                            void console.log("Failed to fetch highlights : ", t)
                        }
                        if (!n || !n.ok)
                            return new e.Notice("Sync failed. Please check your API token and try again."),
                            void console.log("Failed to fetch highlights : ", n);
                        {
                            const e = await n.json();
                            if (!e.rows.length)
                                break;
                            if (o && e.total <= r && (r = e.total,
                            o = !o),
                            l += e.rows.length,
                            s = [...s, ...e.rows],
                            t)
                                break
                        }
                    }
                    return s
                }
```

I have confirmed that I am using the up-to-date version here:

![image](https://user-images.githubusercontent.com/57813331/144249602-a5693a54-6fd0-4d53-8459-0a610c222bfb.png)

**Comment by weichenw** [comment] 2021-12-02 11:29
@mschrader15 Thanks, mate. I have merged and bumped the version

**Comment by mschrader15** [comment] 2021-12-02 13:00
@weichenw no problem!

**Closed** 2021-12-11 04:14 UTC
